### ISSUE TITLE
Reduction Bytes format

### ISSUE THREAD

**Issue by ogrosko** [Scarbous/mr_tinypng#4]
In BE module reduction bytes format are not so user friendly.
You use custom viewHelper for bytes formating with following labels
`'labels' => array(' ', ' Ki', ' Mi', ' Gi', ' Ti', ' Pi', ' Ei', ' Zi', ' Yi')`

and it's not so user friendly, I thing

You can use buildin viewHelper

`You save: <b>{reduction -> f:Format.Bytes()}</b>`

which is much more better. imho ;)

**Comment by Scarbous** [comment]
Hi ogrosko,
 #I changed it.
